import { Metadata } from "next";
import ContentfulPullContent from "./components/ContentfulPullContent";
import ContentfulPushContent from "./components/ContentfulPushContent";
import { ProductSelector } from "./components/ProductSelector";
import WindowListener from "./components/WindowListener/WindowListener";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen items-center justify-center bg-pink-100 font-sans">
      <WindowListener />
      <div className="flex w-screen flex-col">
        <ProductSelector />
      </div>
      <div className="flex w-screen flex-col md:flex-row justify-center items-start">
        <div className="w-full lg:w-1/2">
          <ContentfulPushContent />
        </div>
        <div className="w-full lg:w-1/2">
          <ContentfulPullContent />
        </div>
      </div>
    </div>
  );
}
